feat: home page
piyushsh25/zenvon pull request #1
Opened 2022-02-13 10:11 UTC by piyushsh25

2022-02-13 12:45 UTC, piyushsh25 commented on index.css
> +@media only screen and (max-width:940px) {
done!

2022-02-14 04:50 UTC, Hamdrive requested changes
Code looks good, apart from requested changes.

2022-02-14 04:50 UTC, Hamdrive commented on index.html
> +                    <a href="">Zevnon</a>
Add a href value, else since it is for homepage atleast either add its path or #

2022-02-14 04:50 UTC, Hamdrive commented on index.html
> +                <input type="text" class="input" placeholder="search zevnom">
typo in ecom name

2022-02-14 04:50 UTC, Hamdrive commented on index.html
> +                            <div class="badge text">0</div>
Use a code formatter, makes it easier to read code

2022-02-14 05:03 UTC, piyushsh25 commented on index.html
> +                            <div class="badge text">0</div>
done!

2022-02-14 05:05 UTC, piyushsh25 commented on index.html
> +                <input type="text" class="input" placeholder="search zevnom">
its zevnon. I fixed the typo in my entire document. I will fix it in netlify too.

2022-02-14 05:06 UTC, piyushsh25 commented on index.html
> +                    <a href="">Zevnon</a>
Done.

2022-02-14 05:16 UTC, merged